- name: "✅ Crear organización en VMware Cloud Director (CloudAPI)"
  ansible.builtin.uri:
    url: "{{ vcd.host }}/cloudapi/1.0.0/orgs"
    method: POST
    headers:
      Accept: "application/json;version={{ vcd.api_version }},application/*+json;version={{ vcd.api_version }}"
      Authorization: "Bearer {{ vcd.access_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ vcd.orgFullName }}"
      displayName: "{{ vcd.orgFullName }}"
      isEnabled: true
      description: "Organización creada automáticamente por Ansible"
    # Aceptamos 400 para poder analizar su contenido en failed_when
    status_code: [200, 201, 409, 400] 
    validate_certs: "{{ vcd.verify_ssl }}"
  register: org_create
  failed_when:
    - org_create.status == 400 and org_create.json.minorErrorCode != 'DUPLICATE_NAME'
    # Fallo
    - org_create.status >= 500
  changed_when: org_create.status == 201


- name: "⚙️ Establecer si la organización ya existía (Idempotencia)"
  ansible.builtin.set_fact:
    org_existed: >
      {{ (org_create.status == 409) or 
         (org_create.status == 400 and org_create.json.minorErrorCode == 'DUPLICATE_NAME') }}

- name: "🔍 Mostrar resultado de creación de la organización"
  ansible.builtin.debug:
    msg: >
      {% if org_create.status == 201 %}
        ✅ Organización '{{ vcd.orgFullName }}' creada correctamente.
      {% elif org_existed %}
        ⚠️ La organización '{{ vcd.orgFullName }}' ya existe (Idempotente).
      {% else %}
        ❌ Error inesperado al crear la organización: {{ org_create }}
      {% endif %}
